testdata <- read.table("household_power_consumption.txt", sep=";", header=TRUE,stringsAsFactors=FALSE)
outdata <- subset(testdata, Date=="1/2/2007"|Date=="2/2/2007")

png("plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))

plot(as.numeric(outdata$Global_active_power), type="l", axes=FALSE, ylab="Global Active Power")
at_tick <- c(0, 1440, 2880)
axis(side = 1, at = at_tick, labels = c("Thu","Fri","Sat"))
axis(2, at=c(0,2,4,6))
box("plot", col="black")

plot(as.numeric(outdata$Voltage), type="l", axes=FALSE, ylab="Voltage",xlab="datetime",ylim=c(233,247))
at_tick <- c(0, 1440, 2880)
axis(side = 1, at = at_tick, labels = c("Thu","Fri","Sat"))
axis(2, at=c(234,238,242,246))
box("plot", col="black")

plot(as.numeric(outdata$Sub_metering_1), type="l", axes=FALSE, ylab="Energy sub metering", xlab="")
lines(as.numeric(outdata$Sub_metering_2),col="red",lwd=1)
lines(as.numeric(outdata$Sub_metering_3),col="blue",lwd=1)
at_tick <- c(0, 1440, 2880)
axis(side = 1, at = at_tick, labels = c("Thu","Fri","Sat"))
axis(2, at=c(0,10,20,30))
box("plot", col="black")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),  lty=c(1,1,1), lwd=c(1,1,1),col=c("black","red","blue"),box.lwd=0) 

plot(as.numeric(outdata$Global_reactive_power), type="l", axes=FALSE, ylab="Global_reactive_power",xlab="datetime")
at_tick <- c(0, 1440, 2880)
axis(side = 1, at = at_tick, labels = c("Thu","Fri","Sat"))
axis(2, at=c(0,0.1,0.2,0.3,0.4,0.5))
box("plot", col="black")

dev.off()
par(mfrow=c(1,1))
