testdata <- read.table("household_power_consumption.txt", sep=";", header=TRUE)
outdata <- subset(testdata, Date=="1/2/2007"|Date=="2/2/2007")
png("plot2.png", width = 480, height = 480)
plot(as.numeric(outdata$Global_active_power)*2/1000, type="l", axes=FALSE, ylab="Global Active Power (kilowatts)")
at_tick <- c(0, 1440, 2880)
axis(side = 1, at = at_tick, labels = c("Thurs","Fri","Sat"))
axis(2, at=c(0,2,4,6))
box("plot", col="black")
dev.off()